/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionListener;
import listeners.InternalFrameListener;
import listeners.MenuItemsImagenListener;

/**
 *
 * @author working
 */
public class JFramePrincipal extends javax.swing.JFrame {
     
     
    /**
     * Creates new form JFramePrincipa  
     */
    public JFramePrincipal() {
        initComponents();
        MenuItemsImagenListener lis = new MenuItemsImagenListener(this);
        
        //Espacial Operaciones
        this.jMenuItem1.addActionListener(new InternalFrameListener(this));
        this.jMenuItemModificarPixeles.addActionListener(lis);
        this.jMenuItemNegativo.addActionListener(lis);
        this.jMenuItemRecortar.addActionListener(lis);
        this.jMenuItemBinario.addActionListener(lis);
        this.jMenuItemGrises.addActionListener(lis);
        this.jMenuItemIluminacion.addActionListener(lis);
        this.jMenuItemBinario2.addActionListener(lis);
        this.jMenuItemBinarioAutomatico.addActionListener(lis);
        this.jMenuItemOtzu.addActionListener(lis);
        this.jMenuItemConvolucion.addActionListener(lis);
        this.jMenuItemRuido.addActionListener(lis);
        
        //Histograma Operaciones
        this.jMenuItemHistogramaN.addActionListener(lis);
        this.jMenuItemExpancionesN.addActionListener(lis);
        
        //Analisis de Frecuencias
        this.jMenuItemFFT.addActionListener(lis);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuOtzu = new javax.swing.JMenu();
        jMenuItemModificarPixeles = new javax.swing.JMenuItem();
        jMenuItemRecortar = new javax.swing.JMenuItem();
        jMenuItemGrises = new javax.swing.JMenuItem();
        jMenuItemNegativo = new javax.swing.JMenuItem();
        jMenuItemBinario = new javax.swing.JMenuItem();
        jMenuItemIluminacion = new javax.swing.JMenuItem();
        jMenuItemBinario2 = new javax.swing.JMenuItem();
        jMenuItemBinarioAutomatico = new javax.swing.JMenuItem();
        jMenuItemOtzu = new javax.swing.JMenuItem();
        jMenuItemConvolucion = new javax.swing.JMenuItem();
        jMenuItemRuido = new javax.swing.JMenuItem();
        jMenuHistogramaNew = new javax.swing.JMenu();
        jMenuItemHistogramaN = new javax.swing.JMenuItem();
        jMenuItemExpancionesN = new javax.swing.JMenuItem();
        jMenuHistogramaNew1 = new javax.swing.JMenu();
        jMenuItemFFT = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1268, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );

        jMenu1.setText("Imagen");

        jMenuItem1.setText("Abrir Imagen");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenuOtzu.setText("Espacial");

        jMenuItemModificarPixeles.setText("Modificar Pixeles");
        jMenuOtzu.add(jMenuItemModificarPixeles);

        jMenuItemRecortar.setText("Recortar Imagen");
        jMenuItemRecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRecortarActionPerformed(evt);
            }
        });
        jMenuOtzu.add(jMenuItemRecortar);

        jMenuItemGrises.setText("Escala de Grises");
        jMenuItemGrises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGrisesActionPerformed(evt);
            }
        });
        jMenuOtzu.add(jMenuItemGrises);

        jMenuItemNegativo.setText("Negativo");
        jMenuItemNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNegativoActionPerformed(evt);
            }
        });
        jMenuOtzu.add(jMenuItemNegativo);

        jMenuItemBinario.setText("Binario");
        jMenuItemBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBinarioActionPerformed(evt);
            }
        });
        jMenuOtzu.add(jMenuItemBinario);

        jMenuItemIluminacion.setText("Iluminacion");
        jMenuItemIluminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIluminacionActionPerformed(evt);
            }
        });
        jMenuOtzu.add(jMenuItemIluminacion);

        jMenuItemBinario2.setText("Binario 2 umbrales");
        jMenuItemBinario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBinario2ActionPerformed(evt);
            }
        });
        jMenuOtzu.add(jMenuItemBinario2);

        jMenuItemBinarioAutomatico.setText("Binario Automatico");
        jMenuItemBinarioAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBinarioAutomaticoActionPerformed(evt);
            }
        });
        jMenuOtzu.add(jMenuItemBinarioAutomatico);

        jMenuItemOtzu.setText("Binarizacion OTZU");
        jMenuItemOtzu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOtzuActionPerformed(evt);
            }
        });
        jMenuOtzu.add(jMenuItemOtzu);

        jMenuItemConvolucion.setText("Convolucion");
        jMenuItemConvolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConvolucionActionPerformed(evt);
            }
        });
        jMenuOtzu.add(jMenuItemConvolucion);

        jMenuItemRuido.setText("Ruido");
        jMenuItemRuido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRuidoActionPerformed(evt);
            }
        });
        jMenuOtzu.add(jMenuItemRuido);

        jMenuBar1.add(jMenuOtzu);

        jMenuHistogramaNew.setText("Histograma");

        jMenuItemHistogramaN.setText("Graficar Histograma2");
        jMenuItemHistogramaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHistogramaNActionPerformed(evt);
            }
        });
        jMenuHistogramaNew.add(jMenuItemHistogramaN);

        jMenuItemExpancionesN.setText("Expansiones");
        jMenuItemExpancionesN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExpancionesNActionPerformed(evt);
            }
        });
        jMenuHistogramaNew.add(jMenuItemExpancionesN);

        jMenuBar1.add(jMenuHistogramaNew);

        jMenuHistogramaNew1.setText("Frecuencias");

        jMenuItemFFT.setText("Filtros");
        jMenuItemFFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFFTActionPerformed(evt);
            }
        });
        jMenuHistogramaNew1.add(jMenuItemFFT);

        jMenuBar1.add(jMenuHistogramaNew1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBinarioAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBinarioAutomaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemBinarioAutomaticoActionPerformed

    private void jMenuItemBinario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBinario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemBinario2ActionPerformed

    private void jMenuItemIluminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIluminacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemIluminacionActionPerformed

    private void jMenuItemBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemBinarioActionPerformed

    private void jMenuItemNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNegativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemNegativoActionPerformed

    private void jMenuItemGrisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGrisesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGrisesActionPerformed

    private void jMenuItemRecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRecortarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRecortarActionPerformed

    private void jMenuItemOtzuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOtzuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemOtzuActionPerformed

    private void jMenuItemHistogramaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistogramaNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemHistogramaNActionPerformed

    private void jMenuItemExpancionesNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExpancionesNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemExpancionesNActionPerformed

    private void jMenuItemConvolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConvolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConvolucionActionPerformed

    private void jMenuItemRuidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRuidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRuidoActionPerformed

    private void jMenuItemFFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFFTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHistogramaNew;
    private javax.swing.JMenu jMenuHistogramaNew1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemBinario;
    private javax.swing.JMenuItem jMenuItemBinario2;
    private javax.swing.JMenuItem jMenuItemBinarioAutomatico;
    private javax.swing.JMenuItem jMenuItemConvolucion;
    private javax.swing.JMenuItem jMenuItemExpancionesN;
    private javax.swing.JMenuItem jMenuItemFFT;
    private javax.swing.JMenuItem jMenuItemGrises;
    private javax.swing.JMenuItem jMenuItemHistogramaN;
    private javax.swing.JMenuItem jMenuItemIluminacion;
    private javax.swing.JMenuItem jMenuItemModificarPixeles;
    private javax.swing.JMenuItem jMenuItemNegativo;
    private javax.swing.JMenuItem jMenuItemOtzu;
    private javax.swing.JMenuItem jMenuItemRecortar;
    private javax.swing.JMenuItem jMenuItemRuido;
    private javax.swing.JMenu jMenuOtzu;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jDesktopPanePrincipal
     */
    public javax.swing.JDesktopPane getjDesktopPanePrincipal() {
        return jDesktopPanePrincipal;
    }

    /**
     * @param jDesktopPanePrincipal the jDesktopPanePrincipal to set
     */
    public void setjDesktopPanePrincipal(javax.swing.JDesktopPane jDesktopPanePrincipal) {
        this.jDesktopPanePrincipal = jDesktopPanePrincipal;
    }
}
