/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import listeners.MenuItemsImagenListener;

/**
 *
 * @author Rogelio Valle
 */
public class JInternalFrameExpansiones extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameExpanciones
     */
    
    private JInternalFrameImagen internal;
    
    public JInternalFrameExpansiones(JInternalFrameImagen internal) {
        this.internal = internal;
        initComponents();
        this.jButtonExpacionLineal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Integer.parseInt(jTextFieldX.getText());
                int y = Integer.parseInt(jTextFieldY.getText());
                BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
                
                Image nueva = espacial.ExpansionesHistograma.expansionLineal(x, y, bi);
                JInternalFrameImagen internalNuevo = new JInternalFrameImagen(nueva);
                internalNuevo.setVisible(true);
                MenuItemsImagenListener.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo);
                //internal.setImagen(nueva);
            }
        });
        
        this.jButtonExpasionLogaritmica.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
                
                Image nueva = espacial.ExpansionesHistograma.expansionLogaritmica(bi);
                JInternalFrameImagen internalNuevo = new JInternalFrameImagen(nueva);
                internalNuevo.setVisible(true);
                MenuItemsImagenListener.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo);
            }
        });
        
        this.jButtonExpasionExponencial.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Integer.parseInt(jTextFieldX.getText());
                BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
                
                Image nueva = espacial.ExpansionesHistograma.expansionExponencial(bi,x);
                JInternalFrameImagen internalNuevo = new JInternalFrameImagen(nueva);
                internalNuevo.setVisible(true);
                MenuItemsImagenListener.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo);
            }
        });
        
        this.jButtonEcualizarHistograma.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
                
                Image nueva = espacial.ExpansionesHistograma.ecualizarImagen(bi);
                JInternalFrameImagen internalNuevo = new JInternalFrameImagen(nueva);
                internalNuevo.setVisible(true);
                MenuItemsImagenListener.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldX = new javax.swing.JTextField();
        jTextFieldY = new javax.swing.JTextField();
        jButtonExpacionLineal = new javax.swing.JButton();
        jButtonExpasionLogaritmica = new javax.swing.JButton();
        jButtonExpasionExponencial = new javax.swing.JButton();
        jButtonEcualizarHistograma = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jButtonExpacionLineal.setText("Espansion Lineal");

        jButtonExpasionLogaritmica.setText("Espansion Logaritmical");

        jButtonExpasionExponencial.setText("Espansion Exponencial");

        jButtonEcualizarHistograma.setText("Ecualizar Histograma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonExpasionLogaritmica, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExpacionLineal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExpasionExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEcualizarHistograma, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButtonExpacionLineal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExpasionLogaritmica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExpasionExponencial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEcualizarHistograma)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEcualizarHistograma;
    private javax.swing.JButton jButtonExpacionLineal;
    private javax.swing.JButton jButtonExpasionExponencial;
    private javax.swing.JButton jButtonExpasionLogaritmica;
    private javax.swing.JTextField jTextFieldX;
    private javax.swing.JTextField jTextFieldY;
    // End of variables declaration//GEN-END:variables
}
