/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Rogelio Valle
 */
public class JInternalFrameIluminacion extends javax.swing.JInternalFrame {
    
    private JInternalFrameImagen internal;
    private Image imagenOriginal;

    /**
     * Creates new form JInternalFrameIluminacion
     */
    public JInternalFrameIluminacion(JInternalFrameImagen internal) {
        this.internal = internal;
        initComponents();
        
        this.imagenOriginal = herramientas.HerramientasImagen.copiarImagen(internal.getImagenOriginal());
        this.jSliderIIluminacion.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                int u = ((JSlider) e.getSource()).getValue();
                Image nueva = espacial.Espacial.modificarIluminacion(imagenOriginal, u);
                internal.setImagen(nueva);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderIIluminacion = new javax.swing.JSlider();

        setClosable(true);
        setIconifiable(true);

        jSliderIIluminacion.setMajorTickSpacing(15);
        jSliderIIluminacion.setMaximum(255);
        jSliderIIluminacion.setMinimum(-255);
        jSliderIIluminacion.setPaintLabels(true);
        jSliderIIluminacion.setPaintTicks(true);
        jSliderIIluminacion.setValue(15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSliderIIluminacion, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSliderIIluminacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSliderIIluminacion;
    // End of variables declaration//GEN-END:variables
}
