/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import listeners.MenuItemsImagenListener;

/**
 *
 * @author Rogelio Valle
 */
public class JInternalFrameRuido extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameRuido
     */
    
    private JInternalFrameImagen internal;
    private Image imagenOriginal;
    
    public JInternalFrameRuido(JInternalFrameImagen internal) {
        this.internal = internal;
        initComponents();
        
        this.imagenOriginal = herramientas.HerramientasImagen.copiarImagen(internal.getImagenOriginal());
        
        this.jButtonRuido.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Integer.parseInt(jTextFieldX.getText());
                Image nueva = espacial.Ruido.GenerarRuidoSal(imagenOriginal, x);
                
                JInternalFrameImagen internalNuevo = new JInternalFrameImagen(nueva);
                internalNuevo.setVisible(true);
                MenuItemsImagenListener.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo);
            }
        });
        
        this.jButtonRuidoPimienta.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Integer.parseInt(jTextFieldX.getText());
                Image nueva = espacial.Ruido.GenerarRuidoPimienta(imagenOriginal, x);
                
                JInternalFrameImagen internalNuevo = new JInternalFrameImagen(nueva);
                internalNuevo.setVisible(true);
                MenuItemsImagenListener.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo);
            }
        });
        
        this.jButtonRuidoMixto.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Integer.parseInt(jTextFieldX.getText());
                Image nueva = espacial.Ruido.GenerarRuidoMixto(imagenOriginal, x);
                
                JInternalFrameImagen internalNuevo = new JInternalFrameImagen(nueva);
                internalNuevo.setVisible(true);
                MenuItemsImagenListener.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo);
            }
        });
        
        this.jButtonReduccionMedia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int width = imagenOriginal.getWidth(internal);
                int heigth = imagenOriginal.getHeight(internal);
                int dim = width * heigth;
                Image nueva = espacial.Ruido.reduccionPorMedia(imagenOriginal, 10);
                
                JInternalFrameImagen internalNuevo = new JInternalFrameImagen(nueva);
                internalNuevo.setVisible(true);
                MenuItemsImagenListener.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldX = new javax.swing.JTextField();
        jButtonRuido = new javax.swing.JButton();
        jButtonRuidoMixto = new javax.swing.JButton();
        jButtonRuidoPimienta = new javax.swing.JButton();
        jButtonReduccionMedia = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jButtonRuido.setText("Sal");

        jButtonRuidoMixto.setText("Mixto");

        jButtonRuidoPimienta.setText("Pimienta");

        jButtonReduccionMedia.setText("Reduccion Media");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRuidoPimienta, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRuidoMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRuido, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButtonReduccionMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButtonRuido)
                .addGap(18, 18, 18)
                .addComponent(jButtonRuidoPimienta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRuidoMixto)
                .addGap(54, 54, 54)
                .addComponent(jButtonReduccionMedia)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReduccionMedia;
    private javax.swing.JButton jButtonRuido;
    private javax.swing.JButton jButtonRuidoMixto;
    private javax.swing.JButton jButtonRuidoPimienta;
    private javax.swing.JTextField jTextFieldX;
    // End of variables declaration//GEN-END:variables
}
