/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;

/**
 *
 * @author Rogelio Valle
 */
public class JinternalFrameFiltros extends javax.swing.JInternalFrame {

    /**
     * Creates new form JinternalFrameEscalaGrises
     */
    
    private JInternalFrameImagen internal;
    
    public JinternalFrameFiltros(JInternalFrameImagen internal) {
        this.internal = internal;
        initComponents();
        
        this.jButtonEscalaGrises.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                BufferedImage b1 = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
                for(int i=0; i<b1.getWidth(); i++){
                    for(int j=0; j<b1.getHeight(); j++){
                        //Se obtiene el color de la imagen
                        Color c = new Color(b1.getRGB(i, j));
                        //Se calcula la media de tonalidades
                        int media = (c.getRed()+c.getGreen()+c.getBlue())/3;
                        //Mando el nuevo color a la imagen
                        b1.setRGB(i, j, new Color(media,media,media).getRGB());
                    }
                }
                Image escalaGrises = herramientas.HerramientasImagen.toImage(b1);
                internal.setImagen(escalaGrises);
            }
        });
        
        this.jButtonNegativo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                BufferedImage b1 = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
                for(int i=0; i<b1.getWidth(); i++){
                    for(int j=0; j<b1.getHeight(); j++){
                        //Se obtiene el color de la imagen
                        Color c = new Color(b1.getRGB(i, j));
                        //Se obtienen los valores RGB de la imagen
                        int r = c.getRed();
                        int g = c.getGreen();
                        int b = c.getBlue();
                        //Se manda la nueva imagen con los colores invertidos
                        b1.setRGB(i, j, new Color(255-r,255-g,255-b).getRGB());
                    }
                }
                Image negativo = herramientas.HerramientasImagen.toImage(b1);
                internal.setImagen(negativo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNegativo = new javax.swing.JButton();
        jButtonEscalaGrises = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jButtonNegativo.setText("Negativo");

        jButtonEscalaGrises.setText("Escala de Grises");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNegativo)
                    .addComponent(jButtonEscalaGrises))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButtonEscalaGrises)
                .addGap(29, 29, 29)
                .addComponent(jButtonNegativo)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEscalaGrises;
    private javax.swing.JButton jButtonNegativo;
    // End of variables declaration//GEN-END:variables
}
