/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import espacial.Convolucion;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import listeners.MenuItemsImagenListener;

/**
 *
 * @author Rogelio Valle
 */
public class JInternalFrameConvolucion extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameConvolucion
     */
    
    private JInternalFrameImagen internal;
    
    public JInternalFrameConvolucion(JInternalFrameImagen internal) {
        this.internal = internal;
        initComponents();
        this.jButtonConvolucion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                double x1 = Double.parseDouble(jTextFieldX1.getText());
                double x2 = Double.parseDouble(jTextFieldX2.getText());
                double x3 = Double.parseDouble(jTextFieldX3.getText());
                double x4 = Double.parseDouble(jTextFieldX4.getText());
                double x5 = Double.parseDouble(jTextFieldX5.getText());
                double x6 = Double.parseDouble(jTextFieldX6.getText());
                double x7 = Double.parseDouble(jTextFieldX7.getText());
                double x8 = Double.parseDouble(jTextFieldX8.getText());
                double x9 = Double.parseDouble(jTextFieldX9.getText());
                int div = Integer.parseInt(jTextFieldDivisor.getText());
                
                BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
                //Convolucion
                double[][] kernel = {{x1,x2,x3},{x4,x5,x6},{x7,x8,x9}};
                Convolucion c = new Convolucion();
                Image nueva = c.Convolucionar(kernel, div, bi);
                JInternalFrameImagen internalNuevo = new JInternalFrameImagen(nueva);
                internalNuevo.setVisible(true);
                MenuItemsImagenListener.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo);
            }
        });
        
        this.jButtonConvolucionKirsch.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int div = Integer.parseInt(jTextFieldDivisor.getText());
                
                BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
                //Convolucion
                Convolucion c = new Convolucion();
                Image nueva = c.aplicarKirsch(div, bi);
                JInternalFrameImagen internalNuevo = new JInternalFrameImagen(nueva);
                internalNuevo.setVisible(true);
                MenuItemsImagenListener.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExpacionLineal = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jTextFieldX1 = new javax.swing.JTextField();
        jTextFieldX2 = new javax.swing.JTextField();
        jTextFieldX7 = new javax.swing.JTextField();
        jTextFieldX5 = new javax.swing.JTextField();
        jTextFieldX4 = new javax.swing.JTextField();
        jTextFieldX3 = new javax.swing.JTextField();
        jTextFieldX6 = new javax.swing.JTextField();
        jTextFieldX9 = new javax.swing.JTextField();
        jTextFieldX8 = new javax.swing.JTextField();
        jButtonConvolucion = new javax.swing.JButton();
        jTextFieldDivisor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonConvolucionKirsch = new javax.swing.JButton();

        jButtonExpacionLineal.setText("Espansion Lineal");

        label1.setText("label1");

        setClosable(true);
        setIconifiable(true);

        jButtonConvolucion.setText("Convolucion");
        jButtonConvolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvolucionActionPerformed(evt);
            }
        });

        jLabel1.setText("Divisor:");

        jButtonConvolucionKirsch.setText("Kirsch");
        jButtonConvolucionKirsch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvolucionKirschActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldX4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldX5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldX6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldX1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldX2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldX3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldX7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldX8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldX9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConvolucionKirsch, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConvolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldX1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldX2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldX3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldX5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldX4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldX6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldX7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldX8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldX9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButtonConvolucion)
                .addGap(28, 28, 28)
                .addComponent(jButtonConvolucionKirsch)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConvolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConvolucionActionPerformed

    private void jButtonConvolucionKirschActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvolucionKirschActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConvolucionKirschActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvolucion;
    private javax.swing.JButton jButtonConvolucionKirsch;
    private javax.swing.JButton jButtonExpacionLineal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldDivisor;
    private javax.swing.JTextField jTextFieldX1;
    private javax.swing.JTextField jTextFieldX2;
    private javax.swing.JTextField jTextFieldX3;
    private javax.swing.JTextField jTextFieldX4;
    private javax.swing.JTextField jTextFieldX5;
    private javax.swing.JTextField jTextFieldX6;
    private javax.swing.JTextField jTextFieldX7;
    private javax.swing.JTextField jTextFieldX8;
    private javax.swing.JTextField jTextFieldX9;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
